"""empty message

Revision ID: d28b47cb56fa
Revises: 598e5baddefa
Create Date: 2017-03-01 11:59:43.532567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28b47cb56fa'
down_revision = '598e5baddefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'notes')
    # ### end Alembic commands ###
